redirects:
  guidelines/certification: your-journey/certification.md
  guidelines/communicate: events/communicate.md
  use-cases/payment-automation/README: use-cases/payment-automation.md
  use-cases/payment-automation/using-tokenized-credit-cards: use-cases/payment-automation.md
  webhooks/README: events/README.md
  webhooks/wh-general: events/wh-general.md
  webhooks/wh-integration: events/wh-integration.md
  webhooks/wh-faq: events/wh-faq.md
  websockets/README: events/websockets.md
